name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build & Release apktool.jar
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/actions/setup-gradle@v6.1.0
        with:
          cache-provider: basic

      - name: Build release
        run: ./gradlew build shadowJar proguard release

      - name: Upload apktool.jar to release
        uses: softprops/action-gh-release@v2
        with:
          files: brut.apktool/apktool-cli/build/libs/apktool_v*.jar
